#!/usr/bin/env bash
# Lowercase every string in the "warnings" arrays of src/data/shows_meta.json.
#
# shows_meta.json is generated by scrape_meta.mjs, so re-scraping will bring the
# upstream capitalisation back. Re-run this script after each scrape, or move the
# transform into scrape_meta.mjs if you want it permanently.
set -euo pipefail

file="${1:-$(dirname "$0")/src/data/shows_meta.json}"

if [[ ! -f "$file" ]]; then
  echo "error: no such file: $file" >&2
  exit 1
fi

tmp="$(mktemp "${TMPDIR:-/tmp}/shows_meta.XXXXXX.json")"
trap 'rm -f "$tmp"' EXIT

jq --indent 2 '
  with_entries(
    if .value.warnings? then
      .value.warnings |= map(ascii_downcase)
    else
      .
    end
  )
' "$file" > "$tmp"

mv "$tmp" "$file"
trap - EXIT

echo "downcased warnings in $file"
